# Filename of the first contact statistics file
contfile1 = '../example/free'

# Filename of the second contact statistics file
contfile2 = '../example/cis'

# Filename of the pdb file
pdbfile = '../example/cypa_wt_nowater.pdb'

library(bio3d.core)
library(bio3d.cna)
source('dcna_path_funs.R')

freqs <- lapply(list(f1=contfile1, f2=contfile2), read.table)
pdb <- read.pdb(pdbfile)


# define source/sink node
src <- 29
sink <- 55

################################################
####### dCNA SUBOPTIMAL PATH ANALYSIS ##########
################################################
net <- buildnet_logodd_ratio(freqs$f1, freqs$f2, pc=0.2)
pa <- cnapath(net, from=src, to=sink, k=500, ncore=4)

print(pa, pdb=pdb)

# Visualize paths with VMD
vmd(pa, pdb=pdb, colors=1, out.prefix="paths", spline=TRUE, mag=0.5)
# Then open VMD and type the following command in the VMD terminal:
#  source paths.vmd

################################################
###### END dCNA SUBOPTIMAL PATH ANALYSIS #######
################################################



if(FALSE) { ## Turn off following calculations by default

#############################################################
####### ALTERNATIVE (-ln|dp|) NETWORK EDGES (dCNA) ##########
#############################################################
net <- buildnet(freqs$f1, freqs$f2, pc=0.0)
pa <- cnapath(net, from=src, to=sink, k=500, ncore=4)
print(pa, pdb=pdb)
#############################################################
####### END ALTERNATIVE (-ln|dp|) NETWORK EDGES (dCNA) ######
#############################################################



##################################################################
####### DYNAMICAL NETWORK (DN) SUBOPTIMAL PATH ANALYSIS ##########
##################################################################
# IMPORTANT NOTE: A cross-correlation matrix file is required to perform a DN analysis.
cij <- as.matrix(read.table("correl.dat")) # Assume the correlation file is named 'correl.dat'
                                           # and is in a plain 2D tabular format (as generated by cpptraj)
net <- buildnet_dn_pcn(freqs$f1, cij, pc=0.75)
pa <- cnapath(net, from=src, to=sink, k=500, ncore=4)
print(pa, pdb=pdb)
######################################################################
####### END DYNAMICAL NETWORK (DN) SUBOPTIMAL PATH ANALYSIS ##########
######################################################################



#########################################################################
####### PROTEIN CONTACT NETWORK (PCN) SUBOPTIMAL PATH ANALYSIS ##########
#########################################################################
net <- buildnet_dn_pcn(freqs$f1, pc=0.75)
pa <- cnapath(net, from=src, to=sink, k=500, ncore=4)
print(pa, pdb=pdb)
#############################################################################
####### END PROTEIN CONTACT NETWORK (PCN) SUBOPTIMAL PATH ANALYSIS ##########
#############################################################################

}
